datadog:
  apiKeyExistingSecret: datadog-secret
  clusterName: argocd-kind
  kubelet:
    tlsVerify: false
  apm:
    instrumentation:
      skipKPITelemetry: true
clusterAgent:
  token: aaaaaaaaat5thjkerhtjkfhgjkdfhgjkdfhgkjfdhgkjh
